spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

server:
  port: ${SERVER_PORT}

springdoc:
  openapi:
    info:
      title: User Service API
      version: 1.0.0
      description: User Service API